# Generated by Django 3.2.9 on 2021-11-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_skill_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message',
        ),
    ]
